---
title: "Landing Page"
subtitle: "@b3lch21"
logo: "logo.png"

header: false
footer: '<p>Theme made with <span class="has-text-danger">❤️</span> by <a href="https://github.com/WalkxCode">Walkx</a></p>' # Set false if you want to hide it.

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" 
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:
  - name: "// services"
    icon: "fas fa-home"
    items:
      - name: "Copy me!"
        logo: "assets/tools/clipboard.png"
        subtitle: "Subtitle text goes here"
        url: "#"
        type: "CopyToClipboard"
        clipboard: "this text will be copied to your clipboard"
      - name: "What's Up Docker"
        logo: "assets/tools/docker.png"
        subtitle: "Docker image update notifier"
        url: "http://192.168.188.2:3001"
        type: "WUD"
      - name: "Weather"
        location: "Zell"
        locationId: "3214108"
        apikey: "e264a21d0c59dd01e0ef4642f70987c4"
        units: "metric"
        background: "square"
        type: "OpenWeather"

  - name: "// homelab"
    icon: "fas fa-link"
    items:
      - name: "Qf4b"
        logo: "assets/tools/qnap.png"
        subtitle: "Qnap web interface!"
        tag: "qf4b"
        tagstyle: "is-primary"
        url: "http://qf4b.fritz.box:8080"
        target: "_blank"
      - name: "PiHole"
        tag: "rpi4"
        logo: "assets/tools/pihole.png"
        type: "PiHole"
        url: "http://rpi4.fritz.box/admin/"
        target: "_blank"
        apikey: "b4e78bcf1d0e181c7bcda1c86aacc80cd53ea4529f7700fc83e1c3fc35ac3a1e"      
      - name: "Portainer"
        tag: "rpi4"
        logo: "assets/tools/portainer.png"
        url: "http://rpi4.fritz.box:9000"
        type: "Portainer"
        apikey: "ptr_Bi6Z6m0lvlnKadxj/Eq/gr23QrVlRfoaIy25/L9035k="
        target: "_blank"
      - name: "ruTorrent"
        tag: "qf4b"
        logo: "assets/tools/rutorrent.png"
        url: "http://qf4b.fritz.box:49154"
        target: "_blank"
        xmlrpc: "http://qf4b.fritz.box:8000"
        type: "Rtorrent"
        rateInterval: 5000 
        torrentInterval: 60000
        username: "rutorrent"
        password: "tnerrotur"
      - name: "Transmission"
        tag: "qf4b"
        logo: "assets/tools/transmission.png"
        url: "http://qf4b.fritz.box:9091/transmission/web/"
        target: "_blank"
      - name: "Plex"
        tag: "qf4b"
        logo: "assets/tools/plex.png"
        url: "http://qf4b.fritz.box:32400/web"
        endpoint: "http://qf4b.fritz.box:8181"
        type: "Tautulli"
        apikey: "<---insert-api-key-here--->"
        target: "_blank"

  - name: "// www"
    icon: "fas fa-play"
    items:
      - name: "homepage"
        logo: "assets/tools/home.png"
        url: "https://iam.f4b.io"
        target: "_blank"
      - name: "Google"
        logo: "assets/tools/google.png"
        url: "https://google.com"
        target: "_blank"
